version: '3.9'

services:
  app:
    build: .
    image: app # need to have image here
    ports:
      - '8080:50051'
    environment:
      RUN: production
      HOST: 'localhost'
      DATABASE_URL: 'postgresql://postgres:root@postgres:5432/postgres?schema=public'
      PORT: '50051'
    links:
      - postgres

  postgres:
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: root
    ports:
      - '5432'